/* eslint no-mixed-operators: 0 */
export const THIN = 10;
export const MEDIUM = 20;
export const THICK = 30;
export const EXTRA_THICK = 40;
export const MAX_CANVAS_SIZE = 500;
export const ICON_SIZE = 55;
export const PAST = "PAST";
export const PRESENT = "PRESENT";
export const FUTURE = "FUTURE";
export const LOW_RESOLUTION = 300;
export const STANDARD_RESOLUTION = 500;
export const HIGH_RESOLUTION = 2500;
